version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: kandke_mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: kandke_sons
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data:
